# This file is created automatically by `pak:::proj_create()`
# Please do not edit this file
.libPaths(unique(c(file.path('r-packages', R.version$platform, getRversion()[,1:2]),.libPaths())))
if (file.exists('~/.Rprofile')) source('~/.Rprofile')
