name: Nighly build

on:
  workflow_dispatch:
    inputs:
      macos:
        description: 'macOS x86_64'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
      macos-arm64:
        description: 'macOS arm64'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
      windows:
        description: 'Windows'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
      linux:
        description: 'Linux (x86_64 & aarch64)'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
      bsd:
        description: '*BSD'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
      deploy:
        description: 'Deploy'
        required: true
        type: choice
        options:
        - 'yes'
        - 'no'
        default: 'yes'
  schedule:
  - cron: '30 5 * * *'

# =========================================================================

jobs:

  debug:
    runs-on: ubuntu-latest
    if: always()
    name: Parameters
    steps:
      - name: Input parameters
        run: |
          echo "macos: ${{ github.event.inputs.macos }}"
          echo "windows: ${{ github.event.inputs.windows }}"
          echo "linux: ${{ github.event.inputs.linux }}"
          echo "macos-arm64: ${{ github.event.inputs.macos-arm64 }}"
          echo "deploy: ${{ github.event.inputs.deploy }}"
          echo "macos: ${{ github.event.inputs.macos == 'yes' }}"
          echo "windows: ${{ github.event.inputs.windows == 'yes' }}"
          echo "linux: ${{ github.event.inputs.linux == 'yes' }}"
          echo "macos-arm64: ${{ github.event.inputs.macos-arm64 == 'yes' }}"
          echo "bsd: ${{ github.event.inputs.bsd == 'yes' }}"
          echo "deploy: ${{ github.event.inputs.deploy == 'yes' }}"

  # -----------------------------------------------------------------------
  macos:
    runs-on: macos-latest
    if: ${{ github.event.inputs.macos == '' || github.event.inputs.macos == 'yes' }}
    name: macOS x86_64 R ${{ matrix.config.rver }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { rig: '3.5',     rver: '3.5' }
          - { rig: '3.6',     rver: '3.6' }
          - { rig: '4.0',     rver: '4.0' }
          - { rig: '4.1',     rver: '4.1' }
          - { rig: '4.2',     rver: '4.2' }
          - { rig: '4.3',     rver: '4.3-x86_64' }
          - { rig: '4.4',     rver: '4.4-x86_64' }
          - { rig: '4.5',     rver: '4.5-x86_64' }
          - { rig: 'release', rver: '4.6-x86_64' }
          - { rig: 'devel',   rver: '4.7-x86_64' }

    steps:

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - name: Install rig
      run: |
        curl -LO https://github.com/r-lib/rig/releases/download/v0.8.0/rig-0.8.0-macOS-x86_64.pkg
        sudo installer -pkg rig*.pkg -target /

    - uses: r-hub/actions/setup-r-sysreqs@main
      with:
        arch: x86_64

    - name: Install R
      run: |
        sudo rig add ${{ matrix.config.rig }} --arch x86_64
        rig default ${{ matrix.config.rver }}

    - name: Build pak binaries
      run: |
        cd tools/build/macos && make build
      env:
        RVERSIONS: ${{ matrix.config.rver }}

    - name: Upload package artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pkg-macos-x86_64-${{ matrix.config.rver }}
        path: tools/build/macos/lib/*/pak_*.tgz
        if-no-files-found: error

  # -----------------------------------------------------------------------

  macos-arm64:
    runs-on: macos-latest
    if: ${{ github.event.inputs.macos-arm64 == '' || github.event.inputs.macos-arm64 == 'yes' }}
    name: macos arm64
    env:
      RVERSIONS: "4.1-arm64 4.2-arm64 4.3-arm64 4.4-arm64 4.5-arm64 4.6 4.7"
      RVERSION_DEFAULT: "4.5-arm64"

    steps:

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - name: Install rig
      run: |
        curl -LO https://github.com/r-lib/rig/releases/download/v0.8.1-beta/rig-0.8.1-macOS-arm64.pkg
        sudo installer -pkg rig*.pkg -target /

    - uses: r-hub/actions/setup-r-sysreqs@main
      with:
        arch: arm64

    - name: Install R
      run: |
        sudo rig add 4.1
        sudo rig add 4.2
        sudo rig add 4.3
        sudo rig add 4.4
        sudo rig add 4.5
        sudo rig add release
        sudo rig add devel
        rig default release

    - name: Build pak binaries
      run: |
        cd tools/build/macos && make build

    - name: Upload package artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pkg-macos-arm64
        path: tools/build/macos/lib/*/pak_*.tgz
        if-no-files-found: error

  # ------------------------------------------------------------------------

  windows:
    runs-on: windows-latest
    if: ${{ github.event.inputs.windows == '' || github.event.inputs.windows == 'yes' }}
    name: Windows x86_64

    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: '3.5' }
          - { r: '3.6' }
          - { r: '4.0' }
          - { r: '4.1' }
          - { r: '4.2' }
          - { r: '4.3' }
          - { r: '4.4' }
          - { r: '4.5' }
          - { r: release  }
          - { r: devel }

    steps:

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - name: git config
      run: |
        git config --global user.name "GHA nightly build"
        git config --global user.email "gaborcsardi@users.noreply.github.com"

    - name: Install rig
      run: |
        Invoke-WebRequest -Uri https://github.com/r-lib/rig/releases/download/v0.8.0/rig-windows-0.8.0.exe -OutFile rig-install.exe
        Start-Process ".\rig-install.exe" -ArgumentList "/verysilent /suppressmsgboxes" -Wait -NoNewWindow

    # no P3M, because a pak bug fails to install glue@1.6.2 from PPM
    - name: Install R and RTools
      run: |
        Foreach($ver in (rig ls --plain)) { rig rm $ver }
        rig add ${{ matrix.config.r }} --without-p3m
        rig add rtools
        choco install zip

    - name: Build pak binaries
      run: |
        cd tools/build/windows && make build

    - name: Upload package artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pkg-windows-${{ matrix.config.r }}
        path: tools/build/windows/lib/*/pak_*.zip
        if-no-files-found: error

  # -----------------------------------------------------------------------

  linux:
    runs-on: ${{ matrix.arch.runner }}
    if: ${{ github.event.inputs.linux == '' || github.event.inputs.linux == 'yes' }}
    name: Linux ${{ matrix.arch.name }} ${{ matrix.flavor }} R ${{ matrix.flavor == 'musl' && matrix.r.musl || matrix.r.glibc }}

    strategy:
      fail-fast: false
      matrix:
        arch:
          - { name: 'x86_64', runner: 'ubuntu-latest' }
          - { name: 'arm64',  runner: 'ubuntu-24.04-arm' }
        flavor: [ musl, glibc ]
        r:
          - { musl: '4.7', glibc: 'devel' }
          - { musl: '4.6', glibc: '4.6.1' }
          - { musl: '4.5', glibc: '4.5.3' }
          - { musl: '4.4', glibc: '4.4.3' }
          - { musl: '4.3', glibc: '4.3.3' }
          - { musl: '4.2', glibc: '4.2.3' }
          - { musl: '4.1', glibc: '4.1.3' }
          - { musl: '4.0', glibc: '4.0.5' }
          - { musl: '3.6', glibc: '3.6.3' }
          - { musl: '3.5', glibc: '3.5.3' }

    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - name: Build
      run: |
        cd tools/build/linux && make ${{ matrix.flavor }}
      env:
        RVERSIONS_MUSL: ${{ matrix.r.musl }}
        RVERSIONS_GLIBC: ${{ matrix.r.glibc }}

    - name: Upload package artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pkg-linux-${{ matrix.arch.name }}-${{ matrix.flavor }}-${{ matrix.flavor == 'musl' && matrix.r.musl || matrix.r.glibc }}
        path: tools/build/linux/out/pak_*-linux-${{ matrix.flavor }}.tar.gz
        if-no-files-found: error

  # ------------------------------------------------------------------------

  bsd:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.bsd == '' || github.event.inputs.bsd == 'yes' }}
    name: BSD

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: 'freebsd', release: '15.0' }
          - { os: 'freebsd', release: '14.2' }
          - { os: 'freebsd', release: '13.4' }
          - { os: 'openbsd', release: '7.8' }
          - { os: 'openbsd', release: '7.7' }
          - { os: 'netbsd' }
          - { os: 'dragonflybsd' }

    steps:

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - uses: r-hub/actions/setup-r-freebsd@main
      if: ${{ matrix.config.os == 'freebsd' }}
      with:
        release: ${{ matrix.config.release }}

    - uses: r-hub/actions/setup-r-openbsd@main
      if: ${{ matrix.config.os == 'openbsd' }}
      with:
        release: ${{ matrix.config.release }}

    - uses: r-hub/actions/setup-r-netbsd@main
      if: ${{ matrix.config.os == 'netbsd' }}

    - uses: r-hub/actions/setup-r-dragonflybsd@main
      if: ${{ matrix.config.os == 'dragonflybsd' }}

    - name: Build pak binary
      run: |
        # this runs on the VM
        install.packages(".", repos = NULL, type = "source", INSTALL_opts = "--build")
      shell: Rscript {0}

    - name: Upload package artifacts
      uses: actions/upload-artifact@v7
      with:
        name: pkg-bsd-${{ matrix.config.os }}-${{ matrix.config.release || 'latest' }}
        path: pak_*.tar.gz
        if-no-files-found: error

  # ------------------------------------------------------------------------

  push:
    runs-on: ubuntu-latest
    needs: [ macos, windows, linux, macos-arm64, bsd ]
    if: always()
    concurrency:
      group: pak-push
      queue: max

    steps:

    - name: Update Ubuntu package db, install pak dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: Install skopeo
      run: |
        sudo apt-get install -y skopeo
        skopeo --version

    - name: git config
      run: |
        git config --global user.name "GHA nightly build"
        git config --global user.email "gaborcsardi@users.noreply.github.com"

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10

    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Create user library
      run: |
        dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
      shell: Rscript {0}

    - name: Install local pak tree
      run: R CMD INSTALL .
      env:
        PAK_BUNDLE: false

    - name: Install deploy dependencies
      run: |
        pak::pkg_install("deps::.", dependencies = "Config/Needs/deploy")
      shell: Rscript {0}

    - name: Download package artifacts
      uses: actions/download-artifact@v8
      with:
        path: dist
        pattern: pkg-*

    - name: Push packages to ghcr.io
      run: |
        files <- list.files(
          "dist",
          pattern = "[.](tgz|zip|tar[.]gz)$",
          recursive = TRUE,
          full.names = TRUE
        )
        cat("Pushing", length(files), "package file(s):\n")
        cat(files, sep = "\n")
        cat("\n")
        pak:::push_packages(normalizePath(files))
      shell: Rscript {0}
      env:
        PAK_GHCR_TOKEN: ${{ secrets.PAK_GHCR_TOKEN }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

  # ------------------------------------------------------------------------

  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.event.inputs.deploy == '' || github.event.inputs.deploy == 'yes') && always() }}
    needs: [ push ]

    steps:

    - name: Update Ubuntu package db
      run: |
        sudo apt-get update

    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 10
        persist-credentials: false

    - name: Install R
      uses: r-lib/actions/setup-r@v2

    - name: Create user library
      run: |
        dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
      shell: Rscript {0}

    - name: Dependencies
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: Install local pak tree
      run: R CMD INSTALL .
      env:
        PAK_BUNDLE: false

    - name: Create repository
      run: |
        pak:::create_pak_repo("repo")
      shell: Rscript {0}

    - name: Deploy to GitHub pages (test)
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        repository-name: r-lib/r-lib.github.io
        token: ${{ secrets.PAK_GHCR_TOKEN }}
        single-commit: true
        clean: true
        branch: test
        folder: repo

    - name: Run tests
      run: |
        testthat::test_local(filter = "^repo$")
      shell: Rscript {0}
      env:
        PAK_TESTS: true

    - name: Deploy to GitHub Pages (prod)
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.8.0
      with:
        repository-name: r-lib/r-lib.github.io
        token: ${{ secrets.PAK_GHCR_TOKEN }}
        single-commit: true
        clean: true
        branch: gh-pages
        folder: repo
